name: 🏅 Badge Request
description: Request a custom badge or suggest a new badge type
title: "[BADGE REQUEST] "
labels: ["badge-request", "community"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🏅 Badge Request
        
        Thank you for contributing to our community badging system! Use this template to:
        - Request a custom badge for a special achievement
        - Suggest a new badge type for the community
        - Report issues with existing badges

  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      description: What type of badge request is this?
      options:
        - Custom Badge Request
        - New Badge Type Suggestion
        - Badge Issue/Fix
    validations:
      required: true

  - type: input
    id: badge-name
    attributes:
      label: Badge Name
      description: What should this badge be called?
      placeholder: e.g., "Hackathon Winner", "Documentation Master"
    validations:
      required: true

  - type: textarea
    id: badge-description
    attributes:
      label: Badge Description
      description: Describe what this badge represents and how it should be earned
      placeholder: Explain the criteria for earning this badge...
    validations:
      required: true

  - type: input
    id: badge-emoji
    attributes:
      label: Badge Emoji/Icon
      description: Suggest an emoji or icon for this badge
      placeholder: 🏆, 📚, 🎨, etc.

  - type: input
    id: xp-value
    attributes:
      label: XP Value
      description: How many XP points should this badge be worth? (1-50)
      placeholder: "10"

  - type: dropdown
    id: badge-rarity
    attributes:
      label: Badge Rarity
      description: How rare should this badge be?
      options:
        - Common (Easy to earn)
        - Rare (Moderate effort)
        - Epic (Significant achievement)
        - Legendary (Exceptional accomplishment)

  - type: textarea
    id: earning-criteria
    attributes:
      label: Earning Criteria
      description: Detailed criteria for how someone can earn this badge
      placeholder: |
        - Complete X number of Y
        - Participate in Z event
        - Achieve milestone A
    validations:
      required: true

  - type: input
    id: evidence-link
    attributes:
      label: Evidence Link (if requesting for yourself)
      description: Link to PR, issue, or other evidence if requesting this badge for yourself
      placeholder: https://github.com/func-Kode/site/pull/123

  - type: checkboxes
    id: terms
    attributes:
      label: Community Guidelines
      description: By submitting this request, you agree to our community guidelines
      options:
        - label: I have read and agree to the [Code of Conduct](CODE_OF_CONDUCT.md)
          required: true
        - label: This badge request aligns with func(Kode) community values
          required: true
        - label: I understand that badge requests are reviewed by maintainers
          required: true