name: Manual Badge Award

on:
  workflow_dispatch:
    inputs:
      badge_type:
        description: 'Badge type to award'
        required: true
        type: choice
        options:
          - event_participation
          - project_submission
          - top_contributor
          - first_pr
          - issue_resolver
          - code_reviewer
      username:
        description: 'GitHub username (without @)'
        required: true
        type: string
      event_name:
        description: 'Event name (for event participation badges)'
        required: false
        type: string
      project_url:
        description: 'Project URL (for project submission badges)'
        required: false
        type: string

jobs:
  award-manual-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Award Badge
        run: |
          node .github/scripts/award-badge.js \
            --badge-type "${{ github.event.inputs.badge_type }}" \
            --username "${{ github.event.inputs.username }}" \
            --event-name "${{ github.event.inputs.event_name }}" \
            --project-url "${{ github.event.inputs.project_url }}"

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🏅 Manually awarded ${{ github.event.inputs.badge_type }} badge to @${{ github.event.inputs.username }}"
          file_pattern: "CONTRIBUTORS.md community/badges/*.json"